version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Kolkata
    versioning-strategy: increase
    open-pull-requests-limit: 10
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "typescript-eslint"
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
      changesets:
        patterns:
          - "@changesets/*"
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Kolkata
    labels:
      - dependencies
