blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/darshankachare/dsk-packages/discussions
    about: Please ask and answer questions in GitHub Discussions.
